"""add_artifact_tags_table

Revision ID: 1c6fed600e07
Revises: 45eae442a6c4
Create Date: 2026-02-07 19:30:50.848694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6fed600e07'
down_revision: Union[str, Sequence[str], None] = '45eae442a6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', 'entity_type', 'entity_id', name='uq_artifact_tag')
    )
    op.create_index('ix_artifact_tags_artifact', 'artifact_tags', ['artifact_id'], unique=False)
    op.create_index('ix_artifact_tags_entity', 'artifact_tags', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artifact_tags_entity', table_name='artifact_tags')
    op.drop_index('ix_artifact_tags_artifact', table_name='artifact_tags')
    op.drop_table('artifact_tags')
    # ### end Alembic commands ###
