"""Add media lab jobs, artifacts, and audit events tables

Revision ID: 45eae442a6c4
Revises: d35e97373ff7
Create Date: 2026-02-06 19:11:05.649750

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45eae442a6c4"
down_revision: str | Sequence[str] | None = "d35e97373ff7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create jobs table
    op.create_table(
        "media_jobs",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("character_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("workflow_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_jobs_character_id"),
        "media_jobs",
        ["character_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_jobs_status"),
        "media_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_jobs_created_at"),
        "media_jobs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_media_jobs_workflow_status",
        "media_jobs",
        ["workflow_type", "status"],
        unique=False,
    )

    # Create artifacts table
    op.create_table(
        "media_artifacts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("artifact_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["job_id"], ["media_jobs.id"], ondelete="CASCADE"),
    )
    op.create_index(
        op.f("ix_media_artifacts_job_id"),
        "media_artifacts",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_artifacts_artifact_type"),
        "media_artifacts",
        ["artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_artifacts_created_at"),
        "media_artifacts",
        ["created_at"],
        unique=False,
    )

    # Create audit_events table
    op.create_table(
        "audit_events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("actor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["job_id"], ["media_jobs.id"], ondelete="CASCADE"),
    )
    op.create_index(
        op.f("ix_audit_events_job_id"),
        "audit_events",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_event_type"),
        "audit_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_created_at"),
        "audit_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_job_timestamp",
        "audit_events",
        ["job_id", "created_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_job_timestamp", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_job_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_media_artifacts_created_at"), table_name="media_artifacts")
    op.drop_index(op.f("ix_media_artifacts_artifact_type"), table_name="media_artifacts")
    op.drop_index(op.f("ix_media_artifacts_job_id"), table_name="media_artifacts")
    op.drop_table("media_artifacts")
    op.drop_index("ix_media_jobs_workflow_status", table_name="media_jobs")
    op.drop_index(op.f("ix_media_jobs_created_at"), table_name="media_jobs")
    op.drop_index(op.f("ix_media_jobs_status"), table_name="media_jobs")
    op.drop_index(op.f("ix_media_jobs_character_id"), table_name="media_jobs")
    op.drop_table("media_jobs")
    # ### end Alembic commands ###
