"""create_character_relationships_table

Revision ID: d35e97373ff7
Revises:
Create Date: 2026-02-04 12:45:16.385257

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d35e97373ff7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "character_relationships",
        sa.Column("from_character_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to_character_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "ROMANTIC",
                "FAMILIAL",
                "ANTAGONISTIC",
                "SIRE_PROGENY",
                "FRIENDSHIP",
                "PROFESSIONAL",
                name="relationshiptype",
            ),
            nullable=False,
        ),
        sa.Column("intensity", sa.Integer(), nullable=False),
        sa.Column("start_episode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("end_episode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_character_id", "to_character_id", "relationship_type", name="uq_relationship_edge"
        ),
    )
    op.create_index(
        op.f("ix_character_relationships_from_character_id"),
        "character_relationships",
        ["from_character_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_character_relationships_to_character_id"),
        "character_relationships",
        ["to_character_id"],
        unique=False,
    )
    op.create_index(
        "ix_relationship_from_to",
        "character_relationships",
        ["from_character_id", "to_character_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_relationship_from_to", table_name="character_relationships")
    op.drop_index(
        op.f("ix_character_relationships_to_character_id"), table_name="character_relationships"
    )
    op.drop_index(
        op.f("ix_character_relationships_from_character_id"), table_name="character_relationships"
    )
    op.drop_table("character_relationships")
    # ### end Alembic commands ###
